/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as Step2Import } from './routes/step2'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const Step2Route = Step2Import.update({
  id: '/step2',
  path: '/step2',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/step2': {
      id: '/step2'
      path: '/step2'
      fullPath: '/step2'
      preLoaderRoute: typeof Step2Import
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/step2': typeof Step2Route
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/step2': typeof Step2Route
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/step2': typeof Step2Route
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/step2'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/step2'
  id: '__root__' | '/' | '/step2'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Step2Route: typeof Step2Route
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Step2Route: Step2Route,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/step2"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/step2": {
      "filePath": "step2.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
